apiVersion: v1
kind: Service
metadata:
  name: service-nginx-color
  namespace: green
spec:
  selector:
    app: nginx-color
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001
  type: NodePort
