apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-mongodb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  volumeName: longhorn-mongodb-pv
  resources:
    requests:
      storage: 5Gi
