apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
spec:
  selector:
    matchLabels:
      type: mongodb-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
