apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      initContainers:
        - name: init-mongo
          image: busybox:1.28
          command: ["sh", "-c", "until nslookup mongo-service.default.svc.cluster.local; do echo Aguardando o Banco de Dados; sleep 2; done"]
      containers:
      - name: api
        image: fabricioveronez/pedelogo-catalogo:1.0.0
        resources:
          requests:
            memory: 32Mi
            cpu: 500m
          limits:
            memory: 64Mi
            cpu: 500m
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /read
            port: 80
            scheme: HTTP
          periodSeconds: 30
        startupProbe:
          httpGet:
            path: /health
            port: 80
            scheme: HTTP
          periodSeconds: 30
        livenessProbe:
          httpGet:
            host: localhost
            path: /health
            port: 80
            scheme: HTTP
          periodSeconds: 30
        envFrom:
        - configMapRef:
            name: api-configmap
        env:
        - name: Mongo__User
          valueFrom:
            secretKeyRef:
              key: MONGO_INITDB_ROOT_USERNAME
              name: mongodb-secret
        - name: Mongo__Password
          valueFrom:
            secretKeyRef:
              key: MONGO_INITDB_ROOT_PASSWORD
              name: mongodb-secret
      # imagePullSecrets:
      #   - name: acr-kubedeve